### PR TITLE
Update GUIs

### PR DESCRIPTION
**Pull request by CedricHirschi**
To use this B_mode plotting, the user has to use the `bmode_configs.json` config set. This could be implemented directly into the configs GUI.

### Further changes
Moved GUI visualization to a seperate thread

### TODO
- Bugfixes from Sergei's side
- Comments/Docstrings
- Remove old visualization code

### CODE REVIEW

**Comment by CedricHirschi** [comment]
### Changes
- Fixed known bugs in the main GUI
- Added a first GUI to manage the USS configuration.

### TODO
- Comments/Docstring
- Remove old visualization code
- Remove old USSConfig API

**Comment by CedricHirschi** [comment]
### Changes
Finished TODOs

**Comment by Sergio5714** [comment]
@CedricHirschi, Nice contribution! I have noticed a couple of minor issues and also left some comments below. Please, address them.
**USS config GUI**:
- [ ] Please remove "Transmitter frequency" (but leave a placeholder for future, later there will be DutyCycle setting for pulses).
- [ ] Please rename "Measuring period" -> "Measurement Period"
- [ ] Default "Number of samples" is 800. That is incorrect. This value is the number of bytes to store all samples. Each sample takes 2 bytes. Therefore, the number of samples is 400. Please, let the user choose the number of samples which are then internally converted into the number of bytes.
- [ ] Reorder the settings' window (group them + add headers as in the attached image)
USS_GUI_template drawio

**Test Jupyter notebook**: 
- [ ] By default, start with activating simple config (one transducer TX and RX). In the user guide, we can further explain how to work with B-mode. Starting with the B-mode config is a bit complex.
- [ ] Rename "b_mode_configs.json" to "tx_rx_configs_bmode.json" to show that this config belongs to the tx_rx_configs type.

**Source files**:
- [ ] In "config_package.py" I see the "dcdc_turnon" is referenced to 80 MHz clock. Actually, the correspondent timer is driven by the LXFT clock. The same as for the measurement period. Please fix.
- [ ] Put the license header with your name to the new added files. Also add your name (e.g. in the 2nd line) to the files with the major updated you added.

**Comment by CedricHirschi** [comment]
@Sergio5714 Thanks for the feedback. I have now implemented the changes.
I know we are leaving the GUI for now, but here are some suggestions from my side:

**Fixes**
- [ ] Right now, the `max_vis_fps` parameter of the `WulpusGuiSingleCh` class is unused. This could be removed or implemented again. I think we can remove it.
- [ ] The number of samples is not dynamic in every class (i.e. `WulpusGuiSingleCh`, `WulpusDongle`), they use fixed values still for acquisition/visualization. I would need confirmation on that my understanding of this parameter is right.

**Features**
- [ ] Pass a `WulpusRxTxConfigGen`/`WulpusRxTxConfigGenGUI` to the `WulpusUssConfigGUI` class, thus all the GUIs will be linked dynamically
- [ ] I still think automatic port handling could be nice. Identify the device via a dropdown (we could filter by PID/VID, if only the dongle/probe is used), the connection/disconnection is done automatically

**Comment by Sergio5714** [comment]
@CedricHirschi Thanks, Cedric! Please address a few minor comments (which you probably forgot):

- [ ]  Please rename `"Measuring period" `->` "Measurement Period"`
- [ ] Please rename default B-mode config also in the jupyter notebook to  `"tx_rx_configs_bmode.json"`

Regarding the `max_vis_fps` parameter, I have just checked your code for visualization. Since your code does not have any sleep statements, it will keep the thread active 100% of the time. If that is true, this is not a desired behavior. Therefore, could you please implement the following:

- [ ] Constrain the visualization frequency of the B-mode plots/A-mode plots. Make the maximum FPS rate configurable through the `max_vis_fps` parameter. Please, put the visualization thread into sleep between the visualization events.
 
Regarding the proposed features:

1. Could you please explain what this feature would bring for the user? What problem is it solving?
2. Nice proposal! However, it is not always 100% useful, since we are using different devices with the same type of the nRF dongle (example - BioWolf platform). Many times we want to use the different systems simultaneously on the same PC. Therefore, we need the flexibility to choose the COM port.

**Comment by CedricHirschi** [comment]
@Sergio5714 I have implemented the oversights. The plots now update with `max_vis_fps`, the progress bar in real time.

Regarding my propositions:
1. This would enable the user changing the RX/TX configs and running a new acquisition instantly without rerunning above cells again.
2. I see the reasoning.

**Comment by CedricHirschi** [comment]
Regarding my first proposition:

- I moved the dongle creation to a seperate cell 
- Streamlined some code in the class that resolves any problems occuring when rerunning the GUI cell.

**Comment by Sergio5714** [comment]
Great, thank you, @CedricHirschi!
Now the visualization is much more efficint from a computational point of view. A user can set up the visualization rate according to the specs of his machine! 

The only thing left is Changelog. This time I will add it manualy (so that you can focus on describing newly added features in the User Guide).

Well done!

**Pull request merged**
